package org.tensa.facecheck.main;

import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Rectangle;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.awt.image.ColorModel;
import java.awt.image.ConvolveOp;
import java.awt.image.IndexColorModel;
import java.awt.image.Kernel;
import java.awt.image.WritableRaster;
import java.io.BufferedInputStream;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;
import java.util.Objects;
import javax.imageio.ImageIO;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JPanel;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.tensa.facecheck.filter.MaskOp;
import org.tensa.facecheck.layer.impl.HiddenSigmoidLayer;
import org.tensa.facecheck.layer.impl.PixelDirectSigmoidLeanringLayer;
import org.tensa.facecheck.layer.impl.PixelsDirectSigmoidOutputLayer;
import org.tensa.facecheck.layer.impl.PixelsDirectInputLayer;
import org.tensa.tensada.matrix.Dominio;
import org.tensa.tensada.matrix.DoubleMatriz;
import org.tensa.tensada.matrix.Indice;

/**
 *
 * @author lorenzo
 */
public class VisLoad extends javax.swing.JFrame {

    private final Logger log = LoggerFactory.getLogger(VisLoad.class);

    private final String baseUrl = "\\img\\originales\\";
    private final String testBaseUrl = "\\img\\procesadas\\";
    private final String weightUrl = "\\data\\";
    
    private final String[] imageName = {"IMG_2869", "IMG_2918","IMG_3071","IMG_3076","IMG_3078","IMG_3079"};

    private final String sufxType = ".jpg";
    private ComboBoxModel comboModel;
    private BufferedImage buffImage ;
    private BufferedImage destBuffImage ;
    private final int kwidth = 27;
    private float[] data;
    private BufferedImage bufferImageFiltered;
    private DoubleMatriz weightsH;
    private DoubleMatriz weightsO;
    private int step;
    private int rebaje;
    private Rectangle learnArea;

    /**
     * Get the value of comboModel
     *
     * @return the value of comboModel
     */
    public ComboBoxModel getComboModel() {
        if(Objects.isNull(comboModel))
            comboModel = new DefaultComboBoxModel(imageName);
            
        return comboModel;
      
    }

    /**
     * Get the value of sufxType
     *
     * @return the value of sufxType
     */
    public String getSufxType() {
        return sufxType;
    }

    /**
     * Get the value of imageName
     *
     * @return the value of imageName
     */
    public String[] getImageName() {
        return imageName;
    }

    /**
     * Get the value of imageName at specified index
     *
     * @param index the index of imageName
     * @return the value of imageName at specified index
     */
    public String getImageName(int index) {
        return this.imageName[index];
    }

    public String getBaseUrl() {
        return baseUrl;
    }

    /**
     * Creates new form visLoad
     */
    public VisLoad() {
        initComponents();
        data = new float[kwidth * kwidth];
        float total =0;
        
        for(int i = 0; i < kwidth * kwidth; i++){
            data[i] = calculaMatriz(i % kwidth, i / kwidth);
            total+= data[i];
            
        }
        
        for(int i =0; i < kwidth * kwidth;i++){
            data[i] /= total / 1.5; 
        }
        learnArea = new Rectangle();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jButton3 = new javax.swing.JButton();
        procesar = new javax.swing.JButton();
        clean = new javax.swing.JButton();
        cargar = new javax.swing.JButton();
        salva = new javax.swing.JButton();
        entrenar = new javax.swing.JCheckBox();
        hiddenLearningRate = new javax.swing.JSpinner();
        outputLearningRate = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        seleccion = new javax.swing.JCheckBox();
        jSplitPane1 = new javax.swing.JSplitPane();
        vista = getNuevaVista();
        respuesta = getNuevaRespuesta();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Vista de carga");

        jButton1.setText("Carga...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Modifica");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(getComboModel());

        jButton3.setText("enmascara");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        procesar.setText("procesar");
        procesar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                procesarActionPerformed(evt);
            }
        });

        clean.setText("Limpiar");
        clean.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cleanActionPerformed(evt);
            }
        });

        cargar.setText("Carga");
        cargar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cargarActionPerformed(evt);
            }
        });

        salva.setText("Salva");
        salva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salvaActionPerformed(evt);
            }
        });

        entrenar.setSelected(true);
        entrenar.setText("entrenar");

        hiddenLearningRate.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 24.0d, 1.0d));

        outputLearningRate.setModel(new javax.swing.SpinnerNumberModel(1.0d, 1.0d, 24.0d, 1.0d));

        jLabel1.setText("aprendisaje");

        seleccion.setText("Selección");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(hiddenLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41)
                        .addComponent(outputLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(procesar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(entrenar)
                        .addGap(18, 18, 18)
                        .addComponent(seleccion)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cargar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(salva))
                    .addComponent(clean))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3)
                    .addComponent(cargar)
                    .addComponent(salva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hiddenLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputLearningRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(clean)
                    .addComponent(entrenar)
                    .addComponent(procesar)
                    .addComponent(seleccion)))
        );

        vista.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        vista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                vistaMouseClicked(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                vistaMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout vistaLayout = new javax.swing.GroupLayout(vista);
        vista.setLayout(vistaLayout);
        vistaLayout.setHorizontalGroup(
            vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 316, Short.MAX_VALUE)
        );
        vistaLayout.setVerticalGroup(
            vistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(vista);

        respuesta.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        javax.swing.GroupLayout respuestaLayout = new javax.swing.GroupLayout(respuesta);
        respuesta.setLayout(respuestaLayout);
        respuestaLayout.setHorizontalGroup(
            respuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 323, Short.MAX_VALUE)
        );
        respuestaLayout.setVerticalGroup(
            respuestaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 234, Short.MAX_VALUE)
        );

        jSplitPane1.setRightComponent(respuesta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String _filename1 = System.getProperty("user.dir") + baseUrl + (String)jComboBox1.getSelectedItem() + sufxType;
        String _filename2 = System.getProperty("user.dir") + testBaseUrl + (String)jComboBox1.getSelectedItem() + sufxType;
        log.info("directorio user <{}>",System.getProperty("user.dir"));
        
        try {
            buffImage = ImageIO.read(new File(_filename1));
            
            destBuffImage = ImageIO.read(new File(_filename2));
            
            java.awt.EventQueue.invokeLater(() -> {
                vista.repaint();
            });
        } catch (IOException ex) {
            log.error("error de archivo <{}>", _filename1, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        
        ConvolveOp conv = new ConvolveOp(new Kernel(kwidth, kwidth, data));
        if(Objects.nonNull(bufferImageFiltered))
            bufferImageFiltered.flush();
        
        bufferImageFiltered = conv.filter(destBuffImage, null);
        destBuffImage = bufferImageFiltered;
        
        java.awt.EventQueue.invokeLater(() -> {
            respuesta.repaint();
        });
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        
        MaskOp conv = new MaskOp();
        conv.setOtherSrc(destBuffImage);
        if(Objects.nonNull(bufferImageFiltered))
            bufferImageFiltered.flush();
        
        bufferImageFiltered = conv.filter(buffImage, null);
        destBuffImage = bufferImageFiltered;
        
        java.awt.EventQueue.invokeLater(() -> {
            vista.repaint();
            respuesta.repaint();
        });
    }//GEN-LAST:event_jButton3ActionPerformed

    private void procesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_procesarActionPerformed

        log.info("iniciando 3...");
        bufferImageFiltered = createCompatibleDestImage(buffImage, null);
        
        int width = buffImage.getWidth();
        int height = buffImage.getHeight();
        float escala = (float)buffImage.getWidth() / (float)vista.getBounds().width;
        Rectangle evalArea = new Rectangle(learnArea);
        evalArea.x = (int) (evalArea.x * escala);
        evalArea.y = (int) (evalArea.y * escala);
        evalArea.width = (int) (evalArea.width * escala);
        evalArea.height = (int) (evalArea.height * escala);
        
        log.info("procesando...");


        new Dominio(width-step, height-step).stream()
                .filter( idx -> ((idx.getFila() % step ==0) && (idx.getColumna()% step == 0)))
                .filter(idx -> (!seleccion.isSelected()) || ( evalArea.contains(idx.getFila(), idx.getColumna())) )
                .sorted((idx1,idx2) -> (int)(2.0*Math.random()-1.0))
                .parallel()
                .forEach(idx -> {
                    int i = idx.getFila();
                    int j = idx.getColumna();

                    PixelsDirectInputLayer simplePixelsInputLayer = new PixelsDirectInputLayer();
                    PixelsDirectInputLayer simplePixelsCompareLayer = new PixelsDirectInputLayer();
                    HiddenSigmoidLayer hiddenLayer = new HiddenSigmoidLayer(weightsH,  Math.pow(10, -(Double)hiddenLearningRate.getValue()));
                    PixelDirectSigmoidLeanringLayer pixelLeanringLayer = null;
                    PixelsDirectSigmoidOutputLayer pixelsOutputLayer = new PixelsDirectSigmoidOutputLayer(weightsO);

                    simplePixelsInputLayer.getConsumers().add(hiddenLayer);

                    if(entrenar.isSelected()){
                        pixelLeanringLayer = new PixelDirectSigmoidLeanringLayer(weightsO, Math.pow(10, -(Double)outputLearningRate.getValue()));
                        hiddenLayer.getConsumers().add(pixelLeanringLayer);
                    
//                        log.info("cargando bloque comparacion <{}><{}>", i, j);
                        BufferedImage comp = destBuffImage.getSubimage(i, j, step, step);
                        simplePixelsCompareLayer.setSrc(comp);
                        simplePixelsCompareLayer.startProduction();
                        pixelLeanringLayer.setCompareToLayer(simplePixelsCompareLayer.getOutputLayer());
                        
                    }

//                    log.info("cargando bloque ejecucion <{}><{}>", i, j);
                    hiddenLayer.getConsumers().add(pixelsOutputLayer);
                    pixelsOutputLayer.setDest(bufferImageFiltered.getSubimage(i, j, step, step));
                    BufferedImage src = buffImage.getSubimage(i, j, step, step);
                    simplePixelsInputLayer.setSrc(src);
                    simplePixelsInputLayer.startProduction();
                    
                    if(entrenar.isSelected()){
                        log.info("      error <{}>", pixelLeanringLayer.getError().get(Indice.D1));
                    }
                });
                
            java.awt.EventQueue.invokeLater(() -> {
                vista.repaint();
                respuesta.repaint();
            });
    }//GEN-LAST:event_procesarActionPerformed

    private void cleanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cleanActionPerformed
        log.info("iniciando 0...");
        step = 101;
        rebaje = 2000;
        
        log.info("iniciando 1...<{},{}>",step*step*3 / rebaje, step*step*3);
        weightsH = (DoubleMatriz)new DoubleMatriz(new Dominio(step*step*3 / rebaje, step*step*3)).matrizUno();
        weightsH = (DoubleMatriz)weightsH.productoEscalar( 1.0 / Math.sqrt( step*step*3 / rebaje * step*step*3 ) );
        
        log.info("iniciando 2...<{},{}>",step*step*3, step*step*3 / rebaje);
        weightsO = (DoubleMatriz)new DoubleMatriz(new Dominio(step*step*3, step*step*3 / rebaje)).matrizUno();
        weightsO = (DoubleMatriz)weightsO.productoEscalar( 1.0 / Math.sqrt( step*step*3 / rebaje * step*step*3 ) );
    }//GEN-LAST:event_cleanActionPerformed

    private void salvaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salvaActionPerformed
        String filename = System.getProperty("user.dir") + weightUrl + "nw.dat";
         try( FileOutputStream fos = new FileOutputStream(filename) )   {
            Integer fila = weightsH.getDominio().getFila();
            Integer columna = weightsH.getDominio().getColumna();
            
            ByteBuffer headBuffer = ByteBuffer.allocate(8);
            headBuffer.order(ByteOrder.LITTLE_ENDIAN);
            
            headBuffer.putInt(fila);
            headBuffer.putInt(columna);
            fos.write(headBuffer.array());
            
            ByteBuffer bodyBuffer = ByteBuffer.allocate(step * step * 3 * 8);
            bodyBuffer.order(ByteOrder.LITTLE_ENDIAN);
            
            for(int j=1; j<=columna;j++){
                bodyBuffer.position(0);
                for(int i=1; i<=fila;i++){
                    bodyBuffer.putDouble(weightsH.get( new Indice(i, j)));
                }
                fos.write(bodyBuffer.array());
            }
            fila = weightsO.getDominio().getFila();
            columna = weightsO.getDominio().getColumna();
            
            headBuffer.position(0);
            headBuffer.order(ByteOrder.LITTLE_ENDIAN);
            
            headBuffer.putInt(fila);
            headBuffer.putInt(columna);
            fos.write(headBuffer.array());
            
            bodyBuffer.position(0);
            bodyBuffer.order(ByteOrder.LITTLE_ENDIAN);
            
            for(int i=1; i<=fila;i++){
                bodyBuffer.position(0);
                for(int j=1; j<=columna;j++){
                    bodyBuffer.putDouble(weightsO.get( new Indice(i, j)));
                }
                fos.write(bodyBuffer.array());
            }
         } catch (FileNotFoundException ex) {
             log.error("error al guardar  pesos", ex);
         } catch (IOException ex) {
             log.error("error al guardar  pesos", ex);             
         }
    }//GEN-LAST:event_salvaActionPerformed

    private void cargarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cargarActionPerformed
        String filename = System.getProperty("user.dir") + weightUrl + "nw.dat";
        
        try (BufferedInputStream bis = new BufferedInputStream(new FileInputStream(filename), 15000 * 1024)) {

            byte[] header = new byte[8];
            byte[] body = new byte[step * step * 3 * 8];
            
            Integer fila;
            Integer columna;
            
            bis.read(header);
            ByteBuffer headBuffer = ByteBuffer.wrap(header);
            headBuffer.order(ByteOrder.LITTLE_ENDIAN);
            fila = headBuffer.getInt();
            columna = headBuffer.getInt();
            
            Dominio dominio = new Dominio(fila, columna);
            
            ByteBuffer bodyBuffer;
            weightsH = new DoubleMatriz(dominio);
            
            for(int j=1; j<=columna;j++){
                bis.read(body);
                bodyBuffer = ByteBuffer.wrap(body);
                bodyBuffer.order(ByteOrder.LITTLE_ENDIAN);
                for(int i=1; i<=fila;i++){
                    weightsH.indexa(i, j, bodyBuffer.getDouble());
                }
            } 
            
            bis.read(header);
            headBuffer = ByteBuffer.wrap(header);
            headBuffer.order(ByteOrder.LITTLE_ENDIAN);
            fila = headBuffer.getInt();
            columna = headBuffer.getInt();
            
            dominio = new Dominio(fila, columna);
            
            weightsO = new DoubleMatriz(dominio);
            
            for(int i=1; i<=fila;i++){
                bis.read(body);
                bodyBuffer = ByteBuffer.wrap(body);
                bodyBuffer.order(ByteOrder.LITTLE_ENDIAN);
                for(int j=1; j<=columna;j++){
                    weightsO.indexa(i , j, bodyBuffer.getDouble());
                }
            }
            
        } catch ( FileNotFoundException ex) {
            log.error("error al cargar pesos", ex);
        } catch (IOException ex) {
            log.error("error al cargar pesos", ex);
        }
    }//GEN-LAST:event_cargarActionPerformed

    private void vistaMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vistaMouseReleased
        int x = evt.getX();
        int y = evt.getY();
        learnArea.width = x - learnArea.x;
        learnArea.height = y - learnArea.y;

        java.awt.EventQueue.invokeLater(() -> {
            vista.repaint();
        });
    }//GEN-LAST:event_vistaMouseReleased

    private void vistaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_vistaMouseClicked
        int x = evt.getX();
        int y = evt.getY();
        learnArea.x = x;
        learnArea.y = y;
    }//GEN-LAST:event_vistaMouseClicked

    public BufferedImage createCompatibleDestImage(BufferedImage src, ColorModel destCM) {
        BufferedImage image;

        int w = src.getWidth();
        int h = src.getHeight();

        WritableRaster wr = null;

        if (destCM == null) {
            destCM = src.getColorModel();
            // Not much support for ICM
            if (destCM instanceof IndexColorModel) {
                destCM = ColorModel.getRGBdefault();
            } else {
                /* Create destination image as similar to the source
                 *  as it possible...
                 */
                wr = src.getData().createCompatibleWritableRaster(w, h);
            }
        }

        if (wr == null) {
            /* This is the case when destination color model
             * was explicitly specified (and it may be not compatible
             * with source raster structure) or source is indexed image.
             * We should use destination color model to create compatible
             * destination raster here.
             */
            wr = destCM.createCompatibleWritableRaster(w, h);
        }

        image = new BufferedImage (destCM, wr,
                                   destCM.isAlphaPremultiplied(), null);

        return image;
    }
    
    private float calculaMatriz(int i, int j){
        float retorno;
        float half = (float)kwidth / 2;
        float di = (float) i - half;
        float dj = (float) j - half;
        
        retorno = 0.5f - (float) 1/ ( 1 + di * di + dj * dj);
//        double dist = Math.toRadians(   Math.sqrt((di*di+dj*dj) / (half*half*2)) * 90 ) ;
//        double dist = Math.toRadians(   Math.sqrt((dj*dj) / (half*half*2)) * 90 ) ;
//        if(dist == 0 )
//            retorno = -1; 
//        else
////            retorno = (float) (Math.c(dist)); 
////            retorno = (float) (Math.sin(dist)); 
//            retorno = -(float) (Math.sin(dist) / dist ) ; 
        
//        return  (1- retorno);
        return retorno;
    }
    
    private javax.swing.JPanel getNuevaVista(){
        return new JPanel(true){

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if(Objects.nonNull(buffImage)){
                    Graphics2D localg = (Graphics2D)g;
                    float escala = (float)vista.getBounds().width / (float)buffImage.getWidth();
                    AffineTransform xforM = AffineTransform.getScaleInstance(escala, escala);
                    AffineTransformOp rop = new AffineTransformOp(xforM, AffineTransformOp.TYPE_BILINEAR);
                    localg.drawImage(buffImage, rop, 0     , 0);
                    localg.draw(learnArea);
                    
                }
            }

            
        };
    }
    
    private javax.swing.JPanel getNuevaRespuesta(){
        return new JPanel(true){

            @Override
            protected void paintComponent(Graphics g) {
                super.paintComponent(g);
                if(Objects.nonNull(bufferImageFiltered)){
                    Graphics2D localg = (Graphics2D)g;
                    float escala = (float)respuesta.getBounds().width / (float)bufferImageFiltered.getWidth();
                    AffineTransform xforM = AffineTransform.getScaleInstance(escala, escala);
                    AffineTransformOp rop = new AffineTransformOp(xforM, AffineTransformOp.TYPE_BILINEAR);
                    localg.drawImage(bufferImageFiltered, rop, 0     , 0);
                    
                }
            }

            
        };
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisLoad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VisLoad().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cargar;
    private javax.swing.JButton clean;
    private javax.swing.JCheckBox entrenar;
    private javax.swing.JSpinner hiddenLearningRate;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSpinner outputLearningRate;
    private javax.swing.JButton procesar;
    private javax.swing.JPanel respuesta;
    private javax.swing.JButton salva;
    private javax.swing.JCheckBox seleccion;
    private javax.swing.JPanel vista;
    // End of variables declaration//GEN-END:variables
}
